### ISSUE TITLE
Run Time Speed

### ISSUE THREAD

**Issue by RoyiAvital** [fiji/Stochastic_Denoise#1]
Hi,
How fast is it on real world size images?

Thank You.

**Comment by funkey** [comment]
Hi Roy(?),

I am not sure what you expect to hear. It will depend on the size of the image and your hardware. I can only guess what you mean by a "real world size image". I think the easiest way to get an answer is to just try it, no?

Good luck,
Jan

**Comment by RoyiAvital** [comment]
Hi,
Well I'm thinking about porting it into MATLAB.

Hence I would like to have idea about its performance to have an idea if it is even worth doing.

How is it compared to a Bilateral Filter?
Let's say Full HD images, just to have a notion of size.

Thank You.
